name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Generate assetlinks.json (if needed)
        run: npm run generate-assetlinks

      - name: Build and Deploy
        run: |
          npm run build
          mkdir -p build/.well-known
          cp public/assetlinks.json build/.well-known/
          npm run deploy
